### PR TITLE
Fix #536 #509 #444

### LINKED ISSUE #536: Mayday Stopped Working Again
Mayday does not work in servers and as far as I tell people have posted that they cannot launch it via in game either, this used to happen with an older version of iw6x but last I can remember it was fixed and now its no longer working. If I load if up within the server it does not start the server and it does not work thus I removed it from my map chooser for now until the maps works correctly again. @momo5502 I would like this issue fixed asap so people can play that map as my server is the only extinction server up at the moment and I would say it is the best extinction map that there is and I liked to have it be saved as my default map that people play on when the server is restarted. Thank you!

### PR DESCRIPTION
**Pull request by fedddddd**

### CODE REVIEW

File: src/client/component/scripting.cpp [hunk 1]
```diff
@@ -87,18 +89,24 @@ namespace scripting
 			script_function_table[current_file][function_name] = codePos;
 			scr_set_thread_position_hook.invoke<void>(threadName, codePos);
 		}
-	}
+		
+		int32_t has_config_string_index(const unsigned int csIndex)
```
Comment (diamante0018) [inline src/client/component/scripting.cpp:93]: Unusual to use int32_t as it's not commonly used throughout the source.

**Review by diamante0018 — APPROVED** [review]
Good pr

File: src/client/component/scripting.cpp [hunk 2]
```diff
@@ -104,8 +104,9 @@ namespace scripting
 		unsigned int g_find_config_string_index_stub(const char* name, const int start, const unsigned int max, 
 			const int create, const char* errormsg)
 		{
+			const auto sv_running = game::Dvar_FindVar("sv_running");
 			return g_find_config_string_index.invoke<unsigned int>(name, start, max, 
-				game::SV_Loaded(), errormsg);
+				sv_running->current.integer, errormsg);
```
Comment (diamante0018) [inline src/client/component/scripting.cpp:109]: shouldn't this be .enabled  since it's a bool dvar?

**Review by mjkzy — APPROVED** [review]

**Review by momo5502 — APPROVED** [review]
