### PR TITLE
Fix sending packets longer than 1288 bytes

### LINKED ISSUE #204: RCON Server Crash When At Around 11 Players
Apparently it has something to do with the status code being too long.

### PR DESCRIPTION
**Pull request by skiff**
fixes #204 / #606. redirects Sys_SendPacket to go straight to raw socket without trying to copy data to limited buffer first

### CODE REVIEW

File: src/client/game/symbols.hpp [hunk 1]
```diff
@@ -157,6 +157,7 @@ namespace game
 		0, 0x14041D780
 	};
 	WEAK symbol<bool (const char* s, game::netadr_s* a)> NET_StringToAdr{0, 0x14041D870};
+	WEAK symbol<void(netadr_s*, sockaddr*)> NetadrToSockadr{ 0, 0x1404E53D0 };
```
Comment (diamante0018) [inline src/client/game/symbols.hpp:160]: Remove spaces between { and the addresses please

File: src/client/component/network.cpp [hunk 2]
```diff
@@ -101,6 +101,13 @@ namespace network
 		get_callbacks()[utils::string::to_lower(command)] = callback;
 	}
 
+	int dw_send_to_stub(const int size, const char* src, game::netadr_s* a3)
```
Comment (diamante0018) [inline src/client/component/network.cpp:104]: Couldn't you label the third argument? I'm sure it's easy to find the original name

**Review by diamante0018 — CHANGES_REQUESTED** [review]

**Review by diamante0018 — APPROVED** [review]

**Review by momo5502 — APPROVED** [review]
